name: Build and Push sample api docker images

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Extract GitHub Actions build ID
      run: echo "BUILD_ID=${{ github.run_id }}" >> $GITHUB_ENV

    - name: Build and push Docker image
      run: |
        TAG=$BUILD_ID
        docker buildx create --use --name sample-api
        docker buildx inspect sample-api --bootstrap
        docker buildx build --platform linux/amd64,linux/arm64 \
          -t ghcr.io/${{ github.repository }}/sample-api:$TAG \
          -t ghcr.io/${{ github.repository }}/sample-api:latest \
          --push .

    - name: Output Docker Image Tag
      run: echo "Docker image pushed with tag: $BUILD_ID"

